# With various gcc and clang versions, perform:
#   - debug build
#   - release build

name: gcc+clang
on:
  push:
    branches: 'gh-action-qs'

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-16.04', 'ubuntu-18.04', 'ubuntu-20.04', 'macos-10.15', 'windows-2016' ]
        compiler: [ 'gcc', 'clang' ]
        build: [ 'monchester', 'release' ]
    name: ${{ matrix.compiler }} ${{ matrix.build }} build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '1.0-branch'
      - name: make clean ${{ matrix.build }}
        env:
          CC: ${{ matrix.compiler }}
        run: make clean ${{ matrix.build }} && ./monchester --version
