# With various gcc and clang versions, perform:
#   - debug build
#   - release build

name: gcc+clang
on:
  workflow_dispatch:
    branches: '1.0-branch'

jobs:
  build:
    name: debug build
    runs-on: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: create debug build
        run: make clean monchester && echo && ./monchester --version
      - run: echo "🍏 This job's status is ${{ job.status }}."
