# With various gcc and clang versions, perform:
#   - debug build
#   - release build

name: gcc+clang
on:
  push:
    branches: 'gh-action-qs'

jobs:
  build:
    strategy:
      matrix:
        platform: [ 'ubuntu-16.04', 'ubuntu-18.04', 'ubuntu-20.04' ]
    name: debug build
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '1.0-branch'
      - name: create debug build (gcc)
        run: make clean monchester && echo && ./monchester --version
      - run: echo "🍏 This job's status is ${{ job.status }}."
